#!/bin/bash

rx1=0;
rx2=0;

while true ; do
	rx2=`cat /sys/class/net/ens192/statistics/rx_bytes`
	bytes_per_sec=`expr $rx2 - $rx1`
	kb_per_sec=`expr $bytes_per_sec / 1024`
	mb_per_sec=`expr $kb_per_sec / 1024`
	date=`date`
	if [ $kb_per_sec -gt 500 ]; then
		printf "%s: %s\t%s\t%s\n" "$date" "$bytes_per_sec" "$kb_per_sec" "$mb_per_sec" >> /var/log/chronopolis/transfer_rates
	fi
	sleep 1
	rx1=$rx2
done
